"""Pearch client library for accessing the Pearch API."""

from .client import (
    AsyncPearchClient,
    PearchClient,
    PearchAPIError,
    PearchAuthenticationError,
    PearchValidationError,
)
from .schema import (
    ApiKeyMetadata,
    CustomFilters,
    CustomFiltersMode,
    InsightItem,
    OrganizationMemberApiKeys,
    V1ApiKeyCapabilitiesResponse,
    V1CreateApiKeyRequest,
    V1CreateOrganizationApiKeyResponse,
    V1FindMatchingJobsRequest,
    V1OrganizationApiKeysResponse,
    V1ProfileRequest,
    V1SearchRequest,
    V1UpsertJobsRequest,
    V1ListJobsRequest,
    V1DeleteJobsRequest,
    V2SearchCountRequest,
    V2SearchRequest,
    V2SearchCompanyLeadsRequest,
    SearchRequirement,
    Job,
    ListedJob,
)

__version__ = "0.1.0"
__all__ = [
    "AsyncPearchClient",
    "PearchClient",
    "PearchAPIError",
    "PearchAuthenticationError",
    "PearchValidationError",
    "ApiKeyMetadata",
    "CustomFilters",
    "CustomFiltersMode",
    "InsightItem",
    "OrganizationMemberApiKeys",
    "V1ApiKeyCapabilitiesResponse",
    "V1CreateApiKeyRequest",
    "V1CreateOrganizationApiKeyResponse",
    "V1FindMatchingJobsRequest",
    "V1OrganizationApiKeysResponse",
    "V1ProfileRequest",
    "V1SearchRequest",
    "V1UpsertJobsRequest",
    "V1ListJobsRequest",
    "V1DeleteJobsRequest",
    "V2SearchCountRequest",
    "V2SearchRequest",
    "V2SearchCompanyLeadsRequest",
    "SearchRequirement",
    "Job",
    "ListedJob",
]
