"""Pearch client library for accessing the Pearch API."""

from .client import (
    AsyncPearchClient,
    PearchClient,
    PearchAPIError,
    PearchAuthenticationError,
    PearchValidationError,
)
from .schema import (
    ApiKeyMetadata,
    CustomFilters,
    CustomFiltersMode,
    InsightItem,
    OrganizationMember,
    OrganizationMemberApiKeys,
    OrganizationPendingInvite,
    OrganizationRole,
    V1ApiKeyCapabilitiesResponse,
    V1CreateApiKeyRequest,
    V1CreateOrganizationApiKeyResponse,
    V1FindMatchingJobsRequest,
    V1InviteOrganizationMemberRequest,
    V1InviteOrganizationMemberResponse,
    V1OrganizationApiKeysResponse,
    V1OrganizationMembersResponse,
    V1ProfileRequest,
    V1SearchRequest,
    V1UpdateOrganizationMemberRoleRequest,
    V1UpdateOrganizationMemberRoleResponse,
    V1UpsertJobsRequest,
    V1ListJobsRequest,
    V1DeleteJobsRequest,
    V2SearchCountRequest,
    V2SearchRequest,
    V2SearchCompanyLeadsRequest,
    SearchRequirement,
    Job,
    ListedJob,
)

__version__ = "0.1.0"
__all__ = [
    "AsyncPearchClient",
    "PearchClient",
    "PearchAPIError",
    "PearchAuthenticationError",
    "PearchValidationError",
    "ApiKeyMetadata",
    "CustomFilters",
    "CustomFiltersMode",
    "InsightItem",
    "OrganizationMember",
    "OrganizationMemberApiKeys",
    "OrganizationPendingInvite",
    "OrganizationRole",
    "V1ApiKeyCapabilitiesResponse",
    "V1CreateApiKeyRequest",
    "V1CreateOrganizationApiKeyResponse",
    "V1FindMatchingJobsRequest",
    "V1InviteOrganizationMemberRequest",
    "V1InviteOrganizationMemberResponse",
    "V1OrganizationApiKeysResponse",
    "V1OrganizationMembersResponse",
    "V1ProfileRequest",
    "V1SearchRequest",
    "V1UpdateOrganizationMemberRoleRequest",
    "V1UpdateOrganizationMemberRoleResponse",
    "V1UpsertJobsRequest",
    "V1ListJobsRequest",
    "V1DeleteJobsRequest",
    "V2SearchCountRequest",
    "V2SearchRequest",
    "V2SearchCompanyLeadsRequest",
    "SearchRequirement",
    "Job",
    "ListedJob",
]
